language: go
go:
  - 1.5
  - 1.6
  - tip

env:
  GO15VENDOREXPERIMENT=1
  PATH="$PATH:$HOME/bin"

before_install:
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint

  - mkdir -p ~/bin

  - wget -O ~/lark-0_3_0-linux-amd64.tar.gz https://github.com/bmatsuo/lark/releases/download/v0.3.0/lark-0_3_0-linux-amd64.tar.gz
  - tar -C ~ -xvzf ~/lark-0_3_0-linux-amd64.tar.gz
  - cp ~/lark-0_3_0-linux-amd64/lark ~/bin

  - wget -O ~/glide-0.8.3-linux-amd64.tar.gz https://github.com/Masterminds/glide/releases/download/0.8.3/glide-0.8.3-linux-amd64.tar.gz
  - tar -C ~ -xvzf ~/glide-0.8.3-linux-amd64.tar.gz
  - cp ~/linux-amd64/glide ~/bin

install:
  - lark init

script:
  - lark run test test race=1
